pretrained_model_path: "./pretrained_models/stable-diffusion-v1-5"
pretrained_clip_path: "./pretrained_models/clip-vit-base-patch32"

pretrained_motion_unet_path: "./pretrained_models/motion_unet"
specific_motion_unet_model: "sd15_mmv1.ckpt"

pretrained_poseguider_path: "./pretrained_models/poseguider_stage_1.ckpt"
pretrained_referencenet_path: "./pretrained_models/referencenet_stage_1.ckpt"


savename: null

fusion_blocks: "full"


seed:           [42]
steps:          25
guidance_scale: 7.5
# guidance_scale: 0

source_image:
  - "inputs/applications/source_image/81FyMPk-WIS.mp4"
video_path:
  - "inputs/applications/driving/dwpose/81FyMPk-WIS.mp4"


inference_config: "configs/inference/inference.yaml"
size: 512
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false
